### ISSUE TITLE
Web Component Attributes Observer

### ISSUE THREAD

**Issue by sarbull** [master-atul/react-webcomponentify#1]
Hi, great work!

Does it watch all the attributes added on a html tag / web component? Even if you don't specify what attributes to watch?

```html
<my-component attr1="value1" attr2="value2"></my-component>
```

Best regards

**Comment by master-atul** [comment]
Hi @sarbull  Sorry I totally missed this. Yes it does watch all the attributes without specifying anything. It does this using Mutation observer 
See here: https://github.com/master-atul/react-webcomponentify/blob/a1093c8bf0a132fe8cb450b543f22cf986a0b71c/src/index.js#L17
